<?php

/*
 * Implement hook_preprocess_page
 */
function thp_preprocess_page(&$vars) {
  if ($vars['directory'] != 'themes/seven') {
    drupal_add_js(drupal_get_path('module', 'thp') . '/js/jquery.min.js', 'external');
    drupal_add_js(drupal_get_path('module', 'thp') . '/js/jquery-ui.min.js', 'external');
    
    if (isset($vars['node'])) {
      if ($vars['node']->nid == 4) {
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/countUp.js');
//        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/three.min.js');
//        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/three80.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/three.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/Projector.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/CanvasRenderer.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/threex.domevents.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/build3dBackground.js');
//        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/threeRender80.js');
      }
      if ($vars['node']->nid == 21) {
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/countUp.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/three.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/Projector.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/CanvasRenderer.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/threex.domevents.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/build3dBackground_bottle.js');
      }
      if ($vars['node']->nid == 22) {
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/countUp.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/three.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/Projector.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/CanvasRenderer.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/threex.domevents.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/build3dBackground_label.js');
      }
    }
    
    drupal_add_css(drupal_get_path('module', 'thp') . '/css/odometer-theme-default.css');
    drupal_add_css(drupal_get_path('module', 'thp') . '/css/keyframes.css');
    drupal_add_css(drupal_get_path('module', 'thp') . '/css/tam.css');
    drupal_add_js(drupal_get_path('module', 'thp') . '/js/tam.js');
    drupal_add_css(drupal_get_path('module', 'thp') . '/css/thp.css');
    drupal_add_js(drupal_get_path('module', 'thp') . '/js/thp.js');
    drupal_add_js(drupal_get_path('module', 'thp') . '/js/custom.js');
    
    
    if ($vars['is_front']) {
      drupal_add_css(drupal_get_path('module', 'thp') . '/css/intro.css');
      drupal_add_js(drupal_get_path('module', 'thp') . '/js/intro.js');
    }
  }
}

/**
 * Implements template_preprocess_views_view_unformatted.
 */
function thp_preprocess_views_view_unformatted(&$vars) {
  $view = $vars['view'];
  if ($view->name == 'aseptic' && ($view->current_display == 'block' || $view->current_display == 'block_2') 
          || $view->name == 'bottle' && ($view->current_display == 'block')
          || $view->name == 'label' && ($view->current_display == 'block' || $view->current_display == 'block_2')) {
    $classes_array = $vars['classes_array'];
    $types = ['field_fix_background', 'field_drag_background', 'field_background_360_images'];
    foreach($classes_array as $key => $classes) {
      $bg_type = '';
      foreach($types as $type) {
        if (!empty($view->result[$key]->_field_data['nid']['entity']->$type)) {
          $bg_type = $type;
          break;
        }
      }
      if (!empty($view->result[$key]->_field_data['nid']['entity']->field_follow_with)) {
        $vars['classes_array'][$key] = $classes
                . ' aseptic nid-' . $view->result[$key]->_field_data['nid']['entity']->nid
                . ' follow follow-nid-' . $view->result[$key]->_field_data['nid']['entity']->field_follow_with['und'][0]['target_id']
                . ' ' . $bg_type;
      } 
      else {
        $vars['classes_array'][$key] = $classes . ' aseptic nid-' . $view->result[$key]->_field_data['nid']['entity']->nid . ' ' . $bg_type;
      }
    }
  }
}
