<?php

/*
 * Implement hook_preprocess_page
 */
function thp_preprocess_page(&$vars) {
  if ($vars['directory'] != 'themes/seven') {
    drupal_add_js('http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js', 'external');
    drupal_add_js('https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js', 'external');
    
    if (isset($vars['node'])) {
      if ($vars['node']->nid == 4) {
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/draggable_background.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/three.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/Projector.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/CanvasRenderer.js');
        drupal_add_js(drupal_get_path('module', 'thp') . '/js/treejs/js/build3dBackground.js');
      }
    }
    
    drupal_add_css(drupal_get_path('module', 'thp') . '/css/keyframes.css');
    drupal_add_css(drupal_get_path('module', 'thp') . '/css/tam.css');
    drupal_add_js(drupal_get_path('module', 'thp') . '/js/tam.js');
    drupal_add_css(drupal_get_path('module', 'thp') . '/css/thp.css');
    drupal_add_js(drupal_get_path('module', 'thp') . '/js/thp.js');
    
  }
  
  if ($vars['is_front']) {
    drupal_add_css(drupal_get_path('module', 'thp') . '/css/intro.css');
    drupal_add_js(drupal_get_path('module', 'thp') . '/js/intro.js');
  }
}

/*
 * Implement hook_preprocess_node
 */
//function thp_views_pre_render(&$view) {
//  dpm($view->display['block']);
//}

